# Generated by Django 5.1 on 2024-09-01 12:15

import applicants.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('nric', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('employment_status', models.CharField(choices=[('EMPLOYED', 'EMPLOYED'), ('UNEMPLOYED', 'UNEMPLOYED')], default=applicants.models.EMPLOYMENT['UNEMPLOYED'], max_length=10)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNSPECIFIED', 'UNSPECIFIED')], default=applicants.models.GENDER['UNSPECIFIED'], max_length=11)),
                ('date_of_birth', models.DateField()),
                ('is_main', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=100)),
                ('main_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_applicants', to='applicants.applicant')),
                ('sub_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_applicants', to='applicants.applicant')),
            ],
            options={
                'unique_together': {('main_applicant', 'sub_applicant', 'relation')},
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='household',
            field=models.ManyToManyField(related_name='main_applicant', through='applicants.FamilyMember', to='applicants.applicant'),
        ),
    ]
