# Generated by Django 5.1 on 2024-09-03 16:31

import applicants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_remove_applicant_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='education',
            field=models.CharField(default='Primary', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('DIVORCED', 'DIVORCED'), ('WIDOWED', 'WIDOWED')], default=applicants.models.MARITAL_STATUS['SINGLE'], max_length=10),
        ),
    ]
