# Generated by Django 5.1 on 2024-09-04 05:28

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_applicant_education_applicant_marital_status'),
        ('applications', '0001_initial'),
        ('schemes', '0008_alter_schemecriteria_criteria_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUBMITTED', 'SUBMITTED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default=applications.models.APPLICATION_STATUS['SUBMITTED'], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applicant', 'scheme')},
        ),
    ]
