# Generated by Django 5.1 on 2024-08-31 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=256)),
                ('compare_value', models.CharField(max_length=100)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='schemes.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeGeneralBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='schemes.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeNumericBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='num_benefits', to='schemes.scheme')),
            ],
        ),
    ]
