# Generated by Django 5.1 on 2024-08-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemecriteria',
            old_name='field',
            new_name='criteria_field',
        ),
    ]
