# Generated by Django 5.1 on 2024-08-31 15:08

import schemes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_rename_field_schemecriteria_criteria_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemecriteria',
            name='criteria_operator',
            field=models.CharField(choices=[('LESS_THAN', 'LESS_THAN'), ('LESS_THAN_OR_EQUAL', 'LESS_THAN_OR_EQUAL'), ('EQUAL', 'EQUAL'), ('GREATER_THAN', 'GREATER_THAN'), ('GREATER_THAN_OR_EQUAL', 'GREATER_THAN_OR_EQUAL'), ('LENGTH_LESS_THAN', 'LENGTH_LESS_THAN'), ('LENGTH_LESS_THAN_OR_EQUAL', 'LENGTH_LESS_THAN_OR_EQUAL'), ('LENGTH_EQUAL', 'LENGTH_EQUAL'), ('LENGTH_GREATER_THAN', 'LENGTH_GREATER_THAN'), ('LENGTH_GREATER_THAN_OR_EQUAL', 'LENGTH_GREATER_THAN_OR_EQUAL'), ('STRING_EQUAL', 'STRING_EQUAL')], default=schemes.models.SCHEME_CRITERIA_OPERATOR['EQUAL'], max_length=28),
        ),
    ]
