# Generated by Django 5.1 on 2024-09-01 14:21

import django.db.models.deletion
import schemes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_schemecriteria_criteria_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemecriteria',
            name='scheme',
        ),
        migrations.CreateModel(
            name='CriteriaSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_operator', models.CharField(choices=[('SATISFY_ALL', 'SATISFY_ALL'), ('EITHER_OR', 'EITHER_OR')], default=schemes.models.CRITERIA_SET_OPERATOR['SATISFY_ALL'], max_length=11)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='schemes.criteriaset')),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schemes.scheme')),
            ],
        ),
        migrations.AddField(
            model_name='schemecriteria',
            name='criteria_set',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='criterias', to='schemes.criteriaset'),
            preserve_default=False,
        ),
    ]
