# Generated by Django 5.1 on 2024-09-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0004_remove_schemecriteria_scheme_criteriaset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriaset',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteria_sets', to='schemes.scheme'),
        ),
    ]
