# Generated by Django 5.1 on 2024-09-03 13:37

import django.db.models.deletion
import schemes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0005_alter_criteriaset_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeListCriteria',
            fields=[
                ('schemecriteria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schemes.schemecriteria')),
                ('object_field', models.CharField(max_length=256)),
                ('success', models.IntegerField()),
                ('object_criteria_operator', models.CharField(choices=[('LESS_THAN', 'LESS_THAN'), ('LESS_THAN_OR_EQUAL', 'LESS_THAN_OR_EQUAL'), ('EQUAL', 'EQUAL'), ('GREATER_THAN', 'GREATER_THAN'), ('GREATER_THAN_OR_EQUAL', 'GREATER_THAN_OR_EQUAL')], default=schemes.models.SCHEME_CRITERIA_OPERATOR['EQUAL'], max_length=28)),
            ],
            bases=('schemes.schemecriteria',),
        ),
    ]
