# Generated by Django 5.1 on 2024-09-03 15:43

import schemes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0006_schemelistcriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemecriteria',
            name='criteria_field_type',
            field=models.CharField(choices=[('STRING', 'STRING'), ('DATE', 'DATE'), ('LENGTH', 'LENGTH'), ('OBJECT', 'OBJECT'), ('NUMERIC', 'NUMERIC')], default=schemes.models.CRITERIA_FIELD_TYPES['STRING'], max_length=28),
        ),
        migrations.AlterField(
            model_name='schemecriteria',
            name='compare_value',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='schemecriteria',
            name='criteria_operator',
            field=models.CharField(choices=[('LESS_THAN', 'LESS_THAN'), ('EQUAL', 'EQUAL'), ('GREATER_THAN', 'GREATER_THAN'), ('LENGTH_LESS_THAN', 'LENGTH_LESS_THAN'), ('LENGTH_EQUAL', 'LENGTH_EQUAL'), ('LENGTH_GREATER_THAN', 'LENGTH_GREATER_THAN'), ('STRING_EQUAL', 'STRING_EQUAL'), ('DATE_BEFORE', 'DATE_BEFORE'), ('DATE_AFTER', 'DATE_AFTER'), ('DATE_EQUAL', 'DATE_EQUAL'), ('YEARS_AFTER', 'YEARS_AFTER'), ('YEARS_EQUAL', 'YEARS_EQUAL'), ('YEARS_BEFORE', 'YEARS_BEFORE'), ('MONTHS_AFTER', 'MONTHS_AFTER'), ('MONTHS_EQUAL', 'MONTHS_EQUAL'), ('MONTHS_BEFORE', 'MONTHS_BEFORE')], default=schemes.models.SCHEME_CRITERIA_OPERATOR['EQUAL'], max_length=28),
        ),
        migrations.DeleteModel(
            name='SchemeListCriteria',
        ),
    ]
