# Generated by Django 5.1 on 2024-09-04 04:40

import schemes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0007_schemecriteria_criteria_field_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemecriteria',
            name='criteria_operator',
            field=models.CharField(choices=[('LESS_THAN', 'LESS_THAN'), ('LESS_THAN_EQUAL', 'LESS_THAN_EQUAL'), ('EQUAL', 'EQUAL'), ('GREATER_THAN_EQUAL', 'GREATER_THAN_EQUAL'), ('GREATER_THAN', 'GREATER_THAN'), ('LENGTH_LESS_THAN', 'LENGTH_LESS_THAN'), ('LENGTH_LESS_THAN_EQUAL', 'LENGTH_LESS_THAN_EQUAL'), ('LENGTH_EQUAL', 'LENGTH_EQUAL'), ('LENGTH_GREATER_THAN', 'LENGTH_GREATER_THAN'), ('LENGTH_GREATER_THAN_EQUAL', 'LENGTH_GREATER_THAN_EQUAL'), ('STRING_EQUAL', 'STRING_EQUAL'), ('DATE_BEFORE', 'DATE_BEFORE'), ('DATE_AFTER', 'DATE_AFTER'), ('DATE_EQUAL', 'DATE_EQUAL'), ('YEARS_AFTER', 'YEARS_AFTER'), ('YEARS_EQUAL', 'YEARS_EQUAL'), ('YEARS_BEFORE', 'YEARS_BEFORE'), ('MONTHS_AFTER', 'MONTHS_AFTER'), ('MONTHS_EQUAL', 'MONTHS_EQUAL'), ('MONTHS_BEFORE', 'MONTHS_BEFORE')], default=schemes.models.SCHEME_CRITERIA_OPERATOR['EQUAL'], max_length=28),
        ),
    ]
